### ISSUE TITLE
Expanded wiki documentation

### ISSUE THREAD

**Issue by andrewcreekmore** [mklabs/ue4-targetsystemplugin#23]
Fantastic work on this plugin!

I’d like to humbly offer a few potential adjustments to the wiki, made with the overall aim of improving clarity and increasing accessibility for relative newcomers to UE and/or UE plugins (as a recent newbie myself): https://github.com/andrewcreekmore/ue4-targetsystemplugin/wiki 

Summary of changes:

**Setup**
A few typos were fixed, along with the following edits:
> _Original_: “If you start off from the Third Person Template, you can skip this step”

“If your project already starts off from the Third Person Template, or if you simply don't wish to use the provided example Test map, you can skip this step” 

> _Original_: “TargetSystemTargetableInterface: A simple interface you can use on your targetable actors to enable or prevent the targeting on this specific Actor. It has a single method `IsTargetable` which return false by default, and can be overridden to plug-in your custom logic to prevent the targeting for this Actor (like a `IsAlive` state, or if the health of this character is > 0)” 

“`TargetSystemTargetableInterface`: A simple interface you can use on your targetable actors to enable (or prevent) the targeting of this specific Actor. It has a single method `IsTargetable` which returns false by default, and can be overridden to plug-in your custom logic to prevent the targeting of this Actor (e.g., an `IsAlive` state being true could cause `IsTargetable` to return false; the health of the character being > 0 could cause `IsTargetable` to return true, etc)”

> _Original_: “The first step is to attach the `TargetSystemComponent` UActorComponent to your Player Character. In the Third Person Blueprint template, you can do so with `ThirdPersonCharacter` Blueprint.”

“The first step is to attach the `TargetSystemComponent` UActorComponent to your Player Character's Blueprint. For example, if you used the Third Person Blueprint template, you would attach this component to the `ThirdPersonCharacter` Blueprint. Click "add component" and search for Target System, then click to select it. It should now appear in your Player Character's list of components, underneath CharacterMovement.”

> _Original_: “By default, the `TargetLockedOnWidgetClass` is set to the UMG Widget included in this plugin. You can override and extend this Widget or use a custom one.”

“The Locked On Widget is the visual icon that appears over the targeted actor, indicating what the Player Character is currently locked on to. By default, the `TargetLockedOnWidgetClass` is set to the UMG Widget included in this plugin. You can override and extend this Widget or use a custom one.”

> _Original_: “This step is optional, but lets you further define when and how an Actor should be targetable. It can be handy to prevent the Actor from being targeted if it is dead or depending on another state. First, you should add the interface to the `TargetableActors`:”

“This step is optional, but lets you further define when and how an Actor should be targetable. It can be handy to prevent the Actor from being targeted if it is dead or depending on another state. First, you should add the interface to the `TargetableActors` you want to allow the Player Character to target, such as an enemy. To do so, go to that Actor's Blueprint and choose Class Settings, which will change the right-hand Details pane. In this pane, find Interfaces, click Add, and search for and choose `TargetSystemTargetableInterface`:”

> _Original_: “In this setup, this is simply done on the same `ThirdPersonCharacter` blueprint, because that's the Actor we're targeting in this demo.”

“In our example, this is being done on the same `ThirdPersonCharacter` blueprint, because that's the Actor we're targeting in this demo - but typically speaking, this interface is added to non-player characters such as enemies.”

**Configuration**
A few typos were fixed, along with the following edits:
> _Original_: “`float BreakLineOfSightDelay`: The amount of time to break line of sight when actor gets behind an Object.”

“`float BreakLineOfSightDelay`: The amount of time (in seconds) after a targeted actor moves behind an Object until line of sight is broken and targeting is lost.”

> _Original_: “`bool AdjustPitchBasedOnDistanceToTarget`: If enabled, the target system will add an offset to the Pitch for the character's camera rotation at close range. The greater it gets the closer the actor gets to its target. It avoids the issue of the Player Character hiding the target at close range.”

“`bool AdjustPitchBasedOnDistanceToTarget`: If enabled, the target system will add an offset to the Pitch for the Player Character’s camera rotation at close range. The closer the actor gets to its target, the greater the pitch adjusts in order to avoid the common issue of the Player Character hiding the target when at close range.”

**Comment by mklabs** [comment]
Hey @andrewcreekmore thanks a bunch! I really appreciate the effort 👍 

Wikis on github by default are only editable by collaborators as far I'm understanding, unless I make it editable to everyone.

https://docs.github.com/en/communities/documenting-your-project-with-wikis/about-wikis

Instead I'm adding you as a collaborator to the repo, you should be able to make edits to the wiki now (when you accept the invite, github should send you an email)

Feel free to make any edits you feel like would improve the documentation! That's huge, thank you.

I may consider moving the documentation from the wiki into the repo itself (they're just markdown files), and maybe host it on github pages like I did for my other plugins on the marketplace. It would make contributing to the docs easier with PRs (although I think you're the first one proposing documentation improvements and helping me making it better 😃)

**Comment by andrewcreekmore** [comment]
@mklabs done! No problem, and thanks for the add! Let me know if you decide to migrate the wiki as you mentioned and could use a hand!

**Comment by mklabs** [comment]
Thank you so so much @andrewcreekmore ! I really really appreciate it!
