### ISSUE TITLE
Lurendium.com does not exist anymore (possibly source of malware too!)

### ISSUE THREAD

**Issue by Nahor** [mklabs/ue4-targetsystemplugin#29]
The "www.lurendium.com" links mentioned in the readme.md are not valid anymore. Following them a first time, I was sent to some website that tried to install an extension/add-on to my browser. The second time, I was redirected to some other website that got flagged by my adblocker as a possible malware source.

**Comment by mklabs** [comment]
Yeah, you're right. Sadly the website is down now. I'll remove the link.

Thanks!

**Comment by mklabs** [comment]
Maybe I can find the website from a few years ago from archives 🤔

**Comment by mklabs** [comment]
Fixed by #30 Thanks @Nahor !
