### ISSUE TITLE
Locked Target while Player Dies causes Unhandled Exception

### ISSUE THREAD

**Issue by rojahuchez** [mklabs/ue4-targetsystemplugin#32]
Fristly - Thank you for this amazing plugin - It's a beautiful thing!.
When I have the target locked and the attacker kills the player (who has the target locked on to the enemy) - the editor crashes with this error:

Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x00000000000001c8

UnrealEditor_TargetSystem!UE::CoreUObject::Private::ResolveObjectHandleNoRead() [Z:\projects\UE_5.2\Engine\Source\Runtime\CoreUObject\Public\UObject\ObjectHandle.h:255]
UnrealEditor_TargetSystem!UTargetSystemComponent::LineTrace() [Z:\projects\UE_proj\EngineSource\5.2\Title\Plugins\TargetSystem\Source\TargetSystem\Private\TargetSystemComponent.cpp:510]
UnrealEditor_TargetSystem!UTargetSystemComponent::ShouldBreakLineOfSight() [Z:\projects\UE_proj\EngineSource\5.2\Title\Plugins\TargetSystem\Source\TargetSystem\Private\TargetSystemComponent.cpp:595]
UnrealEditor_TargetSystem!UTargetSystemComponent::TickComponent() [Z:\projects\UE_proj\EngineSource\5.2\Title\Plugins\TargetSystem\Source\TargetSystem\Private\TargetSystemComponent.cpp:70]
UnrealEditor_Engine
UnrealEditor_Engine
UnrealEditor_Engine
UnrealEditor_Engine
UnrealEditor_Core
UnrealEditor_Core
UnrealEditor_Engine
UnrealEditor_Engine
UnrealEditor_Engine
UnrealEditor_Engine
UnrealEditor_UnrealEd
UnrealEditor_UnrealEd
UnrealEditor_LyraEditor!ULyraEditorEngine::Tick() [Z:\projects\UE_proj\EngineSource\5.2\LyraStarterGame5.2_v0094\Source\LyraEditor\LyraEditorEngine.cpp:39]
UnrealEditor
UnrealEditor
UnrealEditor
UnrealEditor
UnrealEditor
UnrealEditor
kernel32
ntdll

![image](https://github.com/mklabs/ue4-targetsystemplugin/assets/48830110/5721ca14-e9b8-4deb-8bdf-d58c13172283)

**Comment by mklabs** [comment]
Thank you for opening the issue @rojahuchez 

I wasn't able to reproduce the crash in both fresh 5.2 project and Lyra 5.2.

However, I added a few nullptr checks in the method that was crashing on you, it's available on the master branch and you could test it if you'd like (You'd need to git clone the repository into your Lyra Plugins/ folder or pull to latest if you were using git already)

**Comment by mklabs** [comment]
🎉 Great! Thanks for testing locally, I really appreciate it you could confirm the fix locally.

I'll prepare a release and submit a new build to Epic for the marketplace this week.
