### ISSUE TITLE
Directional Movement While Only Targeting

### ISSUE THREAD

**Issue by XoVervo** [mklabs/ue4-targetsystemplugin#37]
I want my character to start having directional movement only when im targeting I know about the "Should Control Rotation" But Im not sure on how to change the animation considering that the plugin is a component so if you could help me with getting the directional movement while targeting that would be great!

**Comment by mklabs** [comment]
Hi, the best is to set `bShouldControlRotation` to false to not have it get in the way.

Then it's a matter of changing your locomotion system from forward facing to strafing mode, and that's entirely up to your project and the locomotion system you use.

Regarding ACharacter and the character movement component, the variables you want to look for and tweak are `bUseControllerRotationYaw` and `bOrientationToMovement`. That's what TargetSystem's `bShouldControlRotation` is doing when turned on.

As for the animation blueprint, and knowing whether you are locked on a target or not, you can use:

* `IsLocked()` - https://github.com/mklabs/ue4-targetsystemplugin/blob/1.3.3/TargetSystem/Source/TargetSystem/Public/TargetSystemComponent.h#L176-L178
* Both [OnTargetLockedOn and OnTargetLockedOff](https://github.com/mklabs/ue4-targetsystemplugin/blob/1.3.3/TargetSystem/Source/TargetSystem/Public/TargetSystemComponent.h#L157-L163) events

Most straightforward is probably to mirror the state of `IsLocked()` method as part of your Blueprint Animation Update graph in an internal bool variable for your animation BP to use in the locomotion graph.

Related: https://www.unrealengine.com/en-US/tech-blog/adapting-lyra-animation-to-your-ue5-game
