### ISSUE TITLE
Random Crashes (Access violation - code c0000005 (first/second chance not available))

### ISSUE THREAD

**Issue by nonamed46** [mklabs/ue4-targetsystemplugin#6]
Hey when testing this the editor crashes with the error log below. I'm having a hard time replicating this, it seems destroying a targeted actor can lead to it, but i've also encountered it when exiting and entering the range while targeting an actor.  Since i did download it from the marketplace i used your screenshots to replicate the system. (I've just stuck with "pawn" as the targetable actor class.
I'm running it on ue 4.21 and windows 64 bit.

Access violation - code c0000005 (first/second chance not available)

UE4Editor_TargetSystem!UTargetSystemComponent::TargetLockOff() [d:\build\++portal+dev-marketplace+full\sync\localbuilds\plugintemp\hostproject\plugins\targetsystem\source\targetsystem\private\targetsystemcomponent.cpp:267]
UE4Editor_TargetSystem!UTargetSystemComponent::TickComponent() [d:\build\++portal+dev-marketplace+full\sync\localbuilds\plugintemp\hostproject\plugins\targetsystem\source\targetsystem\private\targetsystemcomponent.cpp:73]
UE4Editor_Engine!FActorComponentTickFunction::ExecuteTickHelper<<lambda_3709318d6805ded621dc256d05754a1f> >() [d:\build\++ue4\sync\engine\source\runtime\engine\classes\gameframework\actor.h:3143]
UE4Editor_Engine!FActorComponentTickFunction::ExecuteTick() [d:\build\++ue4\sync\engine\source\runtime\engine\private\components\actorcomponent.cpp:800]
UE4Editor_Engine!TGraphTask<FTickFunctionTask>::ExecuteTask() [d:\build\++ue4\sync\engine\source\runtime\core\public\async\taskgraphinterfaces.h:829]
UE4Editor_Core!FNamedTaskThread::ProcessTasksNamedThread() [d:\build\++ue4\sync\engine\source\runtime\core\private\async\taskgraph.cpp:679]
UE4Editor_Core!FNamedTaskThread::ProcessTasksUntilIdle() [d:\build\++ue4\sync\engine\source\runtime\core\private\async\taskgraph.cpp:586]
UE4Editor_Engine!FTickTaskSequencer::ReleaseTickGroup() [d:\build\++ue4\sync\engine\source\runtime\engine\private\ticktaskmanager.cpp:573]
UE4Editor_Engine!FTickTaskManager::RunTickGroup() [d:\build\++ue4\sync\engine\source\runtime\engine\private\ticktaskmanager.cpp:1474]
UE4Editor_Engine!UWorld::RunTickGroup() [d:\build\++ue4\sync\engine\source\runtime\engine\private\leveltick.cpp:783]
UE4Editor_Engine!UWorld::Tick() [d:\build\++ue4\sync\engine\source\runtime\engine\private\leveltick.cpp:1473]
UE4Editor_UnrealEd!UEditorEngine::Tick() [d:\build\++ue4\sync\engine\source\editor\unrealed\private\editorengine.cpp:1726]
UE4Editor_UnrealEd!UUnrealEdEngine::Tick() [d:\build\++ue4\sync\engine\source\editor\unrealed\private\unrealedengine.cpp:403]
UE4Editor!FEngineLoop::Tick() [d:\build\++ue4\sync\engine\source\runtime\launch\private\launchengineloop.cpp:3699]
UE4Editor!GuardedMain() [d:\build\++ue4\sync\engine\source\runtime\launch\private\launch.cpp:174]
UE4Editor!GuardedMainWrapper() [d:\build\++ue4\sync\engine\source\runtime\launch\private\windows\launchwindows.cpp:145]
UE4Editor!WinMain() [d:\build\++ue4\sync\engine\source\runtime\launch\private\windows\launchwindows.cpp:276]
UE4Editor!__scrt_common_main_seh() [f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:283]
kernel32
ntdll

**Comment by nonamed46** [comment]
ooookay now i didnt even have to do anything, it would just crash after 2 minutes


Access violation - code c0000005 (first/second chance not available)

UE4Editor_SlateCore!FSlateBrush::`vftable'()
UE4Editor_TargetSystem!UTargetSystemComponent::TargetLockOff() [d:\build\++portal+dev-marketplace+full\sync\localbuilds\plugintemp\hostproject\plugins\targetsystem\source\targetsystem\private\targetsystemcomponent.cpp:270]
UE4Editor_TargetSystem!UTargetSystemComponent::TickComponent() [d:\build\++portal+dev-marketplace+full\sync\localbuilds\plugintemp\hostproject\plugins\targetsystem\source\targetsystem\private\targetsystemcomponent.cpp:73]
UE4Editor_Engine!FActorComponentTickFunction::ExecuteTickHelper<<lambda_3709318d6805ded621dc256d05754a1f> >() [d:\build\++ue4\sync\engine\source\runtime\engine\classes\gameframework\actor.h:3143]
UE4Editor_Engine!FActorComponentTickFunction::ExecuteTick() [d:\build\++ue4\sync\engine\source\runtime\engine\private\components\actorcomponent.cpp:800]
UE4Editor_Engine!TGraphTask<FTickFunctionTask>::ExecuteTask() [d:\build\++ue4\sync\engine\source\runtime\core\public\async\taskgraphinterfaces.h:829]
UE4Editor_Core!FNamedTaskThread::ProcessTasksNamedThread() [d:\build\++ue4\sync\engine\source\runtime\core\private\async\taskgraph.cpp:679]
UE4Editor_Core!FNamedTaskThread::ProcessTasksUntilIdle() [d:\build\++ue4\sync\engine\source\runtime\core\private\async\taskgraph.cpp:586]
UE4Editor_Engine!FTickTaskSequencer::ReleaseTickGroup() [d:\build\++ue4\sync\engine\source\runtime\engine\private\ticktaskmanager.cpp:573]
UE4Editor_Engine!FTickTaskManager::RunTickGroup() [d:\build\++ue4\sync\engine\source\runtime\engine\private\ticktaskmanager.cpp:1474]
UE4Editor_Engine!UWorld::RunTickGroup() [d:\build\++ue4\sync\engine\source\runtime\engine\private\leveltick.cpp:783]
UE4Editor_Engine!UWorld::Tick() [d:\build\++ue4\sync\engine\source\runtime\engine\private\leveltick.cpp:1473]
UE4Editor_UnrealEd!UEditorEngine::Tick() [d:\build\++ue4\sync\engine\source\editor\unrealed\private\editorengine.cpp:1726]
UE4Editor_UnrealEd!UUnrealEdEngine::Tick() [d:\build\++ue4\sync\engine\source\editor\unrealed\private\unrealedengine.cpp:403]
UE4Editor!FEngineLoop::Tick() [d:\build\++ue4\sync\engine\source\runtime\launch\private\launchengineloop.cpp:3699]
UE4Editor!GuardedMain() [d:\build\++ue4\sync\engine\source\runtime\launch\private\launch.cpp:174]
UE4Editor!GuardedMainWrapper() [d:\build\++ue4\sync\engine\source\runtime\launch\private\windows\launchwindows.cpp:145]
UE4Editor!WinMain() [d:\build\++ue4\sync\engine\source\runtime\launch\private\windows\launchwindows.cpp:276]
UE4Editor!__scrt_common_main_seh() [f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:283]
kernel32
ntdll

**Comment by mklabs** [comment]
Thank you for the report, and sorry for the inconvenience.

I'm using this system a lot on a game I'm developing right now, and didn't have this kind of issue. That's strange.

If possible, could you provide me a sample project for me to download, if it is feasible, not too voluminous and not confidential ? This way I could maybe reproduce the error and see what's going on.

**Comment by nonamed46** [comment]
thank you for your quick response! Ah don't worry your plugin may save us a lot of time, so thanks for providing it for free! You rule!
 I'm a little busy right now^^ but i will try replicating the issue (or at least encountering it once more) Should i come across it again i will cut our project down as much as i can before sending it to you

**Comment by mklabs** [comment]
Closing in. Feel free to reopen if you still have this issue with latest versions.
